/**
 * tests/test_strategy_edge_cases.js
 *
 * Tests for edge cases and defensive fixes in the COW Rebalance Strategy
 * Validates:
 * 1. targetCount > slots.length handling
 * 2. Window initialization with various grid sizes
 * 3. Dust-threshold partials are not created
 * 4. Role assignment doesn't corrupt state
 * 5. Zero budget edge case handling
 * 6. COW immutability: master grid unchanged during planning
 * 7. Rotation actions generated by reconcileGrid
 * 8. Fund invariance during planning
 */

const { OrderManager } = require('../modules/order/manager');
const { ORDER_TYPES, ORDER_STATES, GRID_LIMITS, COW_ACTIONS } = require('../modules/constants');
const { reconcileGrid } = require('../modules/order/utils/validate');
const assert = require('assert');

let testsPassed = 0;
let testsFailed = 0;

async function testAsync(name, fn) {
    try {
        await fn();
        console.log(`✓ ${name}`);
        testsPassed++;
    } catch (err) {
        console.log(`✗ ${name}: ${err.message}`);
        testsFailed++;
    }
}

// Helper to create a manager with custom grid size
function createManagerWithGridSize(gridSize = 14, budgetBuy = 1000, budgetSell = 10) {
    const config = {
        market: 'TEST/USDT',
        assetA: 'TEST',
        assetB: 'USDT',
        startPrice: 100,
        minPrice: 50,
        maxPrice: 200,
        incrementPercent: 5,
        targetSpreadPercent: 2,
        botFunds: { buy: budgetBuy, sell: budgetSell },
        activeOrders: { buy: 3, sell: 3 },
        weightDistribution: { buy: 1.0, sell: 1.0 }
    };

    const mgr = new OrderManager(config);
    mgr.assets = {
        assetA: { symbol: 'TEST', precision: 8 },
        assetB: { symbol: 'USDT', precision: 8 }
    };

    // Initialize funds
    mgr.funds.total = { grid: { buy: budgetBuy, sell: budgetSell } };
    mgr.funds.available = { buy: budgetBuy, sell: budgetSell };
    mgr.accountTotals = { buy: budgetBuy, sell: budgetSell, buyFree: budgetBuy, sellFree: budgetSell };

    // Create grid orders
    const startPrice = 100;
    const increment = 1 + (config.incrementPercent / 100);
    for (let i = 0; i < gridSize; i++) {
        const price = startPrice * Math.pow(increment, i - Math.floor(gridSize / 2));
        const gridId = `grid-${i}`;
        const orderType = i < Math.floor(gridSize / 2) ? ORDER_TYPES.SELL : (i > Math.floor(gridSize / 2) ? ORDER_TYPES.BUY : ORDER_TYPES.SPREAD);

        mgr.orders.set(gridId, {
            id: gridId,
            type: orderType,
            price: Math.round(price * 100) / 100,
            size: 0,
            state: ORDER_STATES.VIRTUAL,
            orderId: null
        });
    }

    return mgr;
}

async function testCase1() {
    const mgr = createManagerWithGridSize(6, 1000, 10);
    mgr.config.activeOrders.buy = 3; // targetCount > available buy slots (2)

    const result = mgr.strategy.calculateTargetGrid({
        frozenMasterGrid: mgr.orders,
        config: mgr.config,
        accountAssets: mgr.assets,
        funds: mgr.getChainFundsSnapshot(),
        fills: [],
        currentBoundaryIdx: mgr.boundaryIdx
    });

    const activeBuyCount = Array.from(result.targetGrid.values())
        .filter(o => o.type === ORDER_TYPES.BUY && o.state === ORDER_STATES.ACTIVE).length;
    const buySlotCount = Array.from(mgr.orders.values())
        .filter(o => o.type === ORDER_TYPES.BUY).length;

    assert(activeBuyCount <= buySlotCount, 'Should not place more orders than available slots');
}

async function testCase2() {
    const mgr = createManagerWithGridSize(20, 1000, 100);

    const result = mgr.strategy.calculateTargetGrid({
        frozenMasterGrid: mgr.orders,
        config: mgr.config,
        accountAssets: mgr.assets,
        funds: mgr.getChainFundsSnapshot(),
        fills: [],
        currentBoundaryIdx: mgr.boundaryIdx
    });

    assert(result !== undefined, 'Should initialize window correctly with large grid');
    assert(result.targetGrid instanceof Map, 'Should return a target grid Map');
    assert(typeof result.boundaryIdx === 'number', 'Should return a boundary index');
}

async function testCase3a() {
    const mgr = createManagerWithGridSize(10, 500, 50);
    const slots = Array.from(mgr.orders.values()).filter(o => o.type === ORDER_TYPES.BUY);

    const dustPercentage = GRID_LIMITS.PARTIAL_DUST_THRESHOLD_PERCENTAGE / 100;
    const idealSize = 10;
    const dustSize = idealSize * dustPercentage;

    const partialSlot = slots[3];
    if (partialSlot) {
        await mgr._updateOrder({
            ...partialSlot,
            type: ORDER_TYPES.BUY,
            orderId: 'partial-buy-1',
            size: dustSize,
            state: ORDER_STATES.PARTIAL
        });

        mgr.funds.available.buy = 100;

        const targetGridResult = mgr.strategy.calculateTargetGrid({
            frozenMasterGrid: mgr.orders,
            config: mgr.config,
            accountAssets: mgr.assets,
            funds: mgr.getChainFundsSnapshot(),
            fills: [],
            currentBoundaryIdx: mgr.boundaryIdx
        });

        const reconcileResult = reconcileGrid(
            mgr.orders,
            targetGridResult.targetGrid,
            targetGridResult.boundaryIdx,
            { logger: () => {}, dustThresholdPercent: GRID_LIMITS.PARTIAL_DUST_THRESHOLD_PERCENTAGE }
        );

        assert(reconcileResult !== undefined, 'Should process MERGE consolidation');
        // Dust orders should not get CREATE actions
        const createsForDust = reconcileResult.actions.filter(
            a => a.type === COW_ACTIONS.CREATE && a.id === partialSlot.id
        );
        assert.strictEqual(createsForDust.length, 0, 'Dust partial should not trigger a CREATE action');
    }
}

async function testCase3b() {
    const mgr = createManagerWithGridSize(10, 500, 50);
    const slots = Array.from(mgr.orders.values()).filter(o => o.type === ORDER_TYPES.BUY);

    const dustPercentage = GRID_LIMITS.PARTIAL_DUST_THRESHOLD_PERCENTAGE / 100;
    const idealSize = 10;
    const largePartialSize = idealSize * (dustPercentage + 0.5);

    const partialSlot = slots[4];
    if (partialSlot) {
        await mgr._updateOrder({
            ...partialSlot,
            type: ORDER_TYPES.BUY,
            orderId: 'partial-buy-2',
            size: largePartialSize,
            state: ORDER_STATES.PARTIAL
        });

        mgr.funds.available.buy = 100;

        const targetGridResult = mgr.strategy.calculateTargetGrid({
            frozenMasterGrid: mgr.orders,
            config: mgr.config,
            accountAssets: mgr.assets,
            funds: mgr.getChainFundsSnapshot(),
            fills: [],
            currentBoundaryIdx: mgr.boundaryIdx
        });

        const reconcileResult = reconcileGrid(
            mgr.orders,
            targetGridResult.targetGrid,
            targetGridResult.boundaryIdx,
            { logger: () => {}, dustThresholdPercent: GRID_LIMITS.PARTIAL_DUST_THRESHOLD_PERCENTAGE }
        );

        assert(reconcileResult !== undefined, 'Should maintain large partial');
    }
}

async function testCase4() {
    const mgr = createManagerWithGridSize(10, 500, 50);

    const result = mgr.strategy.calculateTargetGrid({
        frozenMasterGrid: mgr.orders,
        config: mgr.config,
        accountAssets: mgr.assets,
        funds: mgr.getChainFundsSnapshot(),
        fills: [],
        currentBoundaryIdx: mgr.boundaryIdx
    });

    assert(result !== undefined, 'Should complete target grid calculation without error');
    assert(result.targetGrid instanceof Map, 'Should return a target grid Map');

    // Verify role assignment: all slots should have valid types
    for (const slot of result.targetGrid.values()) {
        assert(
            slot.type === ORDER_TYPES.BUY || slot.type === ORDER_TYPES.SELL || slot.type === ORDER_TYPES.SPREAD,
            `Slot ${slot.id} should have a valid type`
        );
    }
}

async function testCase5() {
    const mgr = createManagerWithGridSize(10, 0, 0);

    const result = mgr.strategy.calculateTargetGrid({
        frozenMasterGrid: mgr.orders,
        config: mgr.config,
        accountAssets: mgr.assets,
        funds: mgr.getChainFundsSnapshot(),
        fills: [],
        currentBoundaryIdx: mgr.boundaryIdx
    });

    const activeWithSize = Array.from(result.targetGrid.values())
        .filter(o => o.state === ORDER_STATES.ACTIVE && o.size > 0);

    assert.strictEqual(activeWithSize.length, 0, 'Should not place orders with zero budget');
}

async function testCase6() {
    console.log('Testing side invariance during COW rebalance...');
    const mgr = createManagerWithGridSize(10, 1000, 1000);

    // Mock some active orders
    const buyOrders = Array.from(mgr.orders.values()).filter(o => o.type === ORDER_TYPES.BUY).slice(0, 2);
    for (const o of buyOrders) {
        await mgr._updateOrder({...o, orderId: 'oid-' + o.id, state: ORDER_STATES.ACTIVE});
    }

    const sellOrders = Array.from(mgr.orders.values()).filter(o => o.type === ORDER_TYPES.SELL).slice(0, 2);
    for (const o of sellOrders) {
        await mgr._updateOrder({...o, orderId: 'oid-' + o.id, state: ORDER_STATES.ACTIVE});
    }

    // Snapshot master grid before rebalance
    const preRebalanceGrid = new Map(mgr.orders);

    // Trigger rebalance
    const result = await mgr.performSafeRebalance();

    assert(result !== undefined, 'Safe rebalance should return result');
    assert(result.workingGrid !== null, 'Should provide a working grid');
    // COW: master grid should be unchanged after planning
    assert.strictEqual(mgr.orders.size, preRebalanceGrid.size, 'Master grid size should not change during planning');
}

async function testCase7() {
    console.log('Testing COW immutability (master grid unchanged during planning)...');
    const mgr = createManagerWithGridSize(10, 1000, 1000);

    // Setup initial state
    const o = Array.from(mgr.orders.values())[0];
    await mgr._updateOrder({...o, orderId: 'oid-'+o.id, state: ORDER_STATES.ACTIVE});

    const preOrders = new Map(mgr.orders);
    const preFunds = JSON.parse(JSON.stringify(mgr.funds));

    // Perform safe rebalance
    const rebalance = await mgr.performSafeRebalance();

    // Verify master grid was NOT modified during planning (COW guarantee)
    assert.deepStrictEqual(
        Array.from(mgr.orders.entries()),
        Array.from(preOrders.entries()),
        'Master grid should remain unchanged after planning'
    );
    assert.deepStrictEqual(mgr.funds, preFunds, 'Funds should remain unchanged after planning');
}

async function testCase8() {
    console.log('Testing rotation actions in COW reconcile...');
    const mgr = createManagerWithGridSize(10, 1000, 1000);

    // Setup: make some orders ACTIVE so they become surplus when boundary shifts
    const orders = Array.from(mgr.orders.values());
    for (const o of orders.slice(0, 3)) {
        await mgr._updateOrder({...o, orderId: 'oid-'+o.id, state: ORDER_STATES.ACTIVE});
    }

    const rebalance = await mgr.performSafeRebalance();

    // Check if rotation-style UPDATE actions exist in the plan
    const rotationActions = rebalance.actions.filter(a => a.type === COW_ACTIONS.UPDATE && a.isRotation);

    if (rotationActions.length > 0) {
        const r = rotationActions[0];
        assert(r.newGridId, 'Rotation action should have newGridId');
        assert(r.orderId, 'Rotation action should have orderId (old order)');
    }
    // Note: if no rotations are needed, that's also valid - just means grid is already balanced
}

async function testCase9() {
    console.log('Testing fund invariance during COW planning...');
    const mgr = createManagerWithGridSize(10, 1000, 1000);

    const fill = Array.from(mgr.orders.values()).filter(o => o.type === ORDER_TYPES.BUY)[0];
    await mgr._updateOrder({...fill, orderId: 'oid-'+fill.id, state: ORDER_STATES.ACTIVE});

    const preFunds = JSON.parse(JSON.stringify(mgr.funds));

    const rebalance = await mgr.performSafeRebalance();

    assert(mgr.orders.get(fill.id).state === ORDER_STATES.ACTIVE, 'Order should remain ACTIVE after planning');
    assert.deepStrictEqual(mgr.funds, preFunds, 'Funds should remain unchanged during COW planning');
}

async function runTests() {
    console.log('Starting Strategy Edge Case Tests...');

    await testAsync('Case 1: targetCount > slots.length', testCase1);
    await testAsync('Case 2: Large grid window init', testCase2);
    await testAsync('Case 3a: MERGE consolidation (dust)', testCase3a);
    await testAsync('Case 3b: Large partial maintenance', testCase3b);
    await testAsync('Case 4: Role assignment', testCase4);
    await testAsync('Case 5: Zero budget handling', testCase5);
    await testAsync('Case 6: Side invariance in safe rebalance', testCase6);
    await testAsync('Case 7: COW immutability', testCase7);
    await testAsync('Case 8: Rotation actions in COW', testCase8);
    await testAsync('Case 9: Fund invariance', testCase9);

    console.log(`\nTests Passed: ${testsPassed}`);
    console.log(`Tests Failed: ${testsFailed}`);

    if (testsFailed > 0) {
        process.exit(1);
    }
}

runTests();
