/**
 * Print Grid Sample
 *
 * Demonstrates the grid structure generated by the Grid module.
 * Creates a sample grid configuration and displays consecutive price levels
 * with the percentage difference between adjacent slots.
 *
 * Usage: tsx scripts/print_grid.ts
 *
 * Output:
 * - Shows sell levels from highest (furthest above market) to market price
 * - Shows buy levels from market price down to lowest (furthest below market)
 * - Each line displays price progression and percentage increment between levels
 */

const Grid = require('../modules/order/grid');
const { DEFAULT_CONFIG } = require('../modules/constants');
const Format = require('../modules/order/format');

/**
 * printGridSample: Create and display a sample grid
 *
 * Creates a grid with test configuration parameters and visualizes the
 * price levels generated. Useful for testing grid generation logic and
 * verifying that price increments are calculated correctly.
 *
 * Configuration:
 * - startPrice: 2000 (reference market price)
 * - minPrice: 1500 (floor for buy orders)
 * - maxPrice: 2600 (ceiling for sell orders)
 * - incrementPercent: 2% (geometric increment between slots)
 * - targetSpreadPercent: 5% (gap between best buy and best sell)
 * - weightDistribution: Uses default distribution from constants
 *
 * Output Format:
 * Each line shows: [Price A] -> [Price B] : [Percentage change]%
 * Shows up to 20 consecutive levels for each side (buy/sell)
 */
function printGridSample() {
  // Define test configuration for grid generation
  const config = {
    startPrice: 2000,
    minPrice: 1500,
    maxPrice: 2600,
    incrementPercent: 2,
    targetSpreadPercent: 5,
    weightDistribution: DEFAULT_CONFIG.weightDistribution
  };

  // Generate order grid using the configuration
  // Grid.createOrderGrid returns { orders, boundaryIdx, initialSpreadCount }
  const { orders, initialSpreadCount } = Grid.createOrderGrid(config);

  // Separate sell and buy orders, extracting just the prices
  const sell = orders.filter((o: any) => o.type === 'sell').map((o: any) => o.price);
  const buy = orders.filter((o: any) => o.type === 'buy').map((o: any) => o.price);

  // Display sell levels from highest (top) down toward market price
  // Sell orders are arranged with highest prices first
  console.log('--- SELL LEVELS (top -> market) ---');
  for (let i = 0; i < Math.min(20, sell.length - 1); i++) {
    // Get consecutive price levels
    const a = sell[i];        // Current (higher) price
    const b = sell[i+1];      // Next (lower) price
    // Calculate percentage change from current to next
    const pct = ((a - b) / a) * 100;
    console.log(`${Format.formatPrice4(a)} -> ${Format.formatPrice4(b)} : ${Format.formatPrice6(pct)}%`);
  }

  // Display buy levels from market price downward
  // Buy orders are arranged with highest prices (closest to market) first
  console.log('\n--- BUY LEVELS (market -> down) ---');
  for (let i = 0; i < Math.min(20, buy.length - 1); i++) {
    // Get consecutive price levels
    const a = buy[i];         // Current (higher) price
    const b = buy[i+1];       // Next (lower) price
    // Calculate percentage change from current to next
    const pct = ((a - b) / a) * 100;
    console.log(`${Format.formatPrice4(a)} -> ${Format.formatPrice4(b)} : ${Format.formatPrice6(pct)}%`);
  }
}

// Execute sample grid visualization
printGridSample();
export {};
