#!/usr/bin/env node
'use strict';

const { spawnSync } = require('child_process');

const testFiles = [
  'tests/test_utils.js',
  'tests/test_order_grid.js',
  'tests/test_logger.js',
  'tests/test_manager.js',
  'tests/test_account_totals.js',
  'tests/connection_test.js',
  'tests/test_key_validation.js',
  'tests/test_subscriptions.js',
  'tests/test_fills.js',
  'tests/test_account_selection.js',
  'tests/test_autoderive.js',
  'tests/test_price_derive.js',
  'tests/test_price_no_positional.js',
  'tests/test_price_orientation.js',
  'tests/test_price_tolerance.js',
  'tests/test_chain_helpers.js',
  'tests/test_unanchored_spread_correction.js',
  'tests/test_spread_redistribution_fallback.js',
  'tests/test_ghost_order_fix.js',
  'tests/test_startup_decision.js',
  'tests/test_partial_order_edge_cases.js',
  'tests/test_integration_partial_complex.js',
  'tests/test_precision_quantization.js',
  'tests/test_precision_integration.js',
  'tests/test_dust_rebalance_logic.js',
  'tests/test_main_loop_sync_fill_rebalance.js',
  'tests/test_periodic_sync_fill_rebalance.js',
  'tests/test_bts_fee_accounting.js',
  'tests/test_multifill_opposite_partial.js',
  'tests/test_accounting_logic.js',
  'tests/test_strategy_logic.js',
  'tests/test_sync_logic.js',
  'tests/test_grid_logic.js',
  'tests/test_manager_logic.js',
  'tests/test_bts_fee_logic.js',
  'tests/test_boundary_sync_logic.js',
  'tests/test_fee_backwards_compat.js',
  'tests/test_layer2_self_healing.js',
  'tests/test_working_grid.js',
  'tests/test_cow_commit_guards.js',
  'tests/test_cow_master_plan.js',
  'tests/test_legacy_cow_projection.js',
  'tests/test_account_bots_draft.js',
  'tests/test_allowedops_policy.js',
  'tests/test_ama_center_snapshot.js',
  'tests/test_ama_slope_model.js',
  'tests/test_asymmetric_bounds.js',
  'tests/test_derivative_chart.js',
  'tests/test_lp_chart.js',
  'tests/test_lp_chart_strategy_loader.js',
  'tests/test_fill_replay_guards.js',
  'tests/repro_phantom_orders.js',
  'tests/test_bot_settings.js',
  'tests/test_cr_planner.js',
  'tests/test_credit_runtime.js',
  'tests/test_dexbot_credit_wiring.js',
  'tests/test_dynamic_weight_override_wiring.js',
  'tests/test_dexbot_maintenance_runtime_dynamic_weights.js',
  'tests/test_dexbot_maintenance_runtime_market_adapter_watchdog.js',
  'tests/test_dexbot_startup_dynamic_weight_wiring.js',
  'tests/test_market_adapter_fixes.js',
  'tests/test_market_adapter_logic.js',
  'tests/test_market_adapter_log_format.js',
  'tests/test_market_adapter_signal_gates.js',
  'tests/test_market_adapter_smoke.js',
  'tests/test_market_adapter_file_lock.js',
  'tests/test_market_adapter_service.js',
  'tests/test_launcher_exports.js',
  'tests/test_unlock_start_main.js',
  'tests/test_bot_daemon_ready_output.js',
  'tests/test_bot_daemon_probe_fallback.js',
  'tests/test_dexbot_daemon_ready_output.js',
  'tests/test_credential_runtime.js',
  'tests/test_credential_session_cache.js',
  'tests/test_credential_controller_cleanup.js',
  'tests/test_credential_daemon.js',
  'tests/test_pm2_logic.js',
  'tests/test_pm2_startup_order.js',
  'claw/tests/test_claw_regressions.ts',
  'claw/tests/test_claw_state_store.ts',
  'claw/tests/test_dexbot_profiles.ts',
  'claw/tests/test_position_manager_watch_health.ts',
  'claw/tests/test_claw_bridge.ts',
  'claw/tests/test_short_mpa_strategy.ts',
  'claw/tests/test_position_health.ts',
  'claw/tests/test_claw_chain_layer.ts',
  'claw/tests/test_claw_domain_logic.ts',
  'claw/tests/test_claw_catalog_and_credentials.ts',
  'claw/tests/test_claw_data_flow.ts',
  'claw/tests/test_position_manager.ts',
  'claw/tests/test_claw_skill_generation.ts',
  'claw/tests/test_claw_manifest_and_matrix.ts',
  'tests/test_native_serial_types.js',
  'tests/test_native_serial_ops.js',
  'tests/test_native_ecc.js',
  'tests/test_native_tx_builder.js',
  'tests/test_native_subscriptions.js',
  'tests/test_native_transport.js',
  'tests/test_native_facade.js',
  'tests/test_native_chain_client.js',
  'tests/test_adapter_client_native.js',
];

for (const testFile of testFiles) {
  const run = spawnSync(process.execPath, ['--import', 'tsx', testFile], {
    stdio: 'inherit',
    cwd: process.cwd(),
    env: process.env,
  });

  if (run.status !== 0) {
    process.exit(run.status || 1);
  }
}
