import { spawnSync } from 'child_process';

// Suppress Node.js circular dependency warnings across all tests.
// NOTE: Mutating process.env here only affects child node processes spawned
// by spawnSync below; the parent process's env is unchanged after this script
// finishes.
process.env.NODE_OPTIONS = process.env.NODE_OPTIONS || '';
if (!process.env.NODE_OPTIONS.includes('--no-warnings')) {
    process.env.NODE_OPTIONS += ' --no-warnings';
}

// Tests that require RUN_LIVE_BITSHARES_TESTS=1 (live blockchain connection).
// They are excluded from `npm test` and run only when the env var is set.
const liveTestFiles = new Set([
  'tests/test_any_pair.ts',
  'tests/test_blockchain_fill_history.ts',
  'tests/test_market_book_xaut.ts',
  'tests/test_market_price.ts',
  'tests/test_trade_history.ts',
  'tests/test_connection_trace.ts',
]);

const testFiles = [
  'claw/tests/test_claw_bridge.ts',
  'claw/tests/test_claw_catalog_and_credentials.ts',
  'claw/tests/test_claw_chain_layer.ts',
  'claw/tests/test_claw_data_flow.ts',
  'claw/tests/test_claw_domain_logic.ts',
  'claw/tests/test_claw_manifest_and_matrix.ts',
  'claw/tests/test_claw_mcp_transport.ts',
  'claw/tests/test_claw_regressions.ts',
  'claw/tests/test_claw_skill_generation.ts',
  'claw/tests/test_claw_state_store.ts',
  'claw/tests/test_dexbot_profiles.ts',
  'claw/tests/test_memu_bridge.ts',
  'claw/tests/test_nullclaw_tmp_integration.ts',
  'claw/tests/test_position_health.ts',
  'claw/tests/test_position_manager.ts',
  'claw/tests/test_position_manager_watch_health.ts',
  'claw/tests/test_short_mpa_strategy.ts',
  'tests/connection_test.ts',
  'tests/repro_phantom_orders.ts',
  'tests/test_account_bots_draft.ts',
  'tests/test_account_selection.ts',
  'tests/test_account_totals.ts',
  'tests/test_accounting_logic.ts',
  'tests/test_adapter_client_native.ts',
  'tests/test_allowedops_policy.ts',
  'tests/test_ama_center_snapshot.ts',
  'tests/test_ama_optimizer_cli.ts',
  'tests/test_ama_slope_model.ts',
  'tests/test_analyze_orders_dynamic_weight.ts',
  'tests/test_any_pair.ts',
  'tests/test_asymmetric_bounds.ts',
  'tests/test_autoderive.ts',
  'tests/test_backtest_ama_sweep_logic.ts',
  'tests/test_batch_fee_schedule_regression.ts',
  'tests/test_blockchain_fill_history.ts',
  'tests/test_bot_daemon_probe_fallback.ts',
  'tests/test_bot_daemon_ready_output.ts',
  'tests/test_bot_settings.ts',
  'tests/test_bot_startup_output.ts',
  'tests/test_bot_supervisor.ts',
  'tests/test_boundary_sync_logic.ts',
  'tests/test_bts_fee_accounting.ts',
  'tests/test_bts_fee_logic.ts',
  'tests/test_build_create_order_args.ts',
  'tests/test_chain_helpers.ts',
  'tests/test_chain_keys_master_password_failure.ts',
  'tests/test_chain_keys_vault.ts',
  'tests/test_cli_whitelist_args.ts',
  'tests/test_connection_timeout_params.ts',
  'tests/test_connection_trace.ts',
  'tests/test_core_fee_accounting.ts',
  'tests/test_cow_commit_guards.ts',
  'tests/test_cow_concurrent_fills.ts',
  'tests/test_cow_divergence_correction.ts',
  'tests/test_cow_fund_validation_precision.ts',
  'tests/test_cow_index_mutation_detection.ts',
  'tests/test_cow_master_plan.ts',
  'tests/test_cow_orchestration_fixes.ts',
  'tests/test_cow_set_mutation_report.ts',
  'tests/test_cow_static_analysis.ts',
  'tests/test_cow_structural_resync.ts',
  'tests/test_cr_planner.ts',
  'tests/test_credential_controller_cleanup.ts',
  'tests/test_credential_daemon.ts',
  'tests/test_credential_daemon_controller_output.ts',
  'tests/test_credential_debt_policy_constraints.ts',
  'tests/test_credential_runtime.ts',
  'tests/test_credential_session_cache.ts',
  'tests/test_credit_runtime.ts',
  'tests/test_critical_bug_fixes.ts',
  'tests/test_debug_orderbook.ts',
  'tests/test_derivative_chart.ts',
  'tests/test_derivative_entry_bias.ts',
  'tests/test_derivative_momentum_gate.ts',
  'tests/test_derivative_signal_trap_regression.ts',
  'tests/test_dexbot_credit_wiring.ts',
  'tests/test_dexbot_daemon_ready_output.ts',
  'tests/test_dexbot_maintenance_runtime_dynamic_weights.ts',
  'tests/test_dexbot_maintenance_runtime_market_adapter_watchdog.ts',
  'tests/test_dexbot_start_master_password_failure_output.ts',
  'tests/test_dexbot_startup_dynamic_weight_wiring.ts',
  'tests/test_dexbot_startup_output.ts',
  'tests/test_dust_cancel_delay_config_migration.ts',
  'tests/test_dust_rebalance_logic.ts',
  'tests/test_dynamic_weight_override_wiring.ts',
  'tests/test_engine_integration.ts',
  'tests/test_extract_operation_results.ts',
  'tests/test_fee_backwards_compat.ts',
  'tests/test_fee_cache.ts',
  'tests/test_fee_cache_twentix.ts',
  'tests/test_fetch_lp_data_logic.ts',
  'tests/test_fill_batch_chunking.ts',
  'tests/test_fill_replay_guards.ts',
  'tests/test_fill_subscription_lifecycle.ts',
  'tests/test_fills.ts',
  'tests/test_fund_cycling_trigger.ts',
  'tests/test_funds.ts',
  'tests/test_ghost_order_fix.ts',
  'tests/test_grid_comparison.ts',
  'tests/test_grid_logic.ts',
  'tests/test_indexdb.ts',
  'tests/test_integration_partial_complex.ts',
  'tests/test_integration_pending_proceeds.ts',
  'tests/test_key_validation.ts',
  'tests/test_kibana_candles.ts',
  'tests/test_launcher_exports.ts',
  'tests/test_layer2_self_healing.ts',
  'tests/test_legacy_cow_projection.ts',
  'tests/test_logger.ts',
  'tests/test_lp_chart_strategy_loader.ts',
  'tests/test_main_loop_sync_fill_rebalance.ts',
  'tests/test_manager.ts',
  'tests/test_manager_logic.ts',
  'tests/test_market_adapter_file_lock.ts',
  'tests/test_market_adapter_fixes.ts',
  'tests/test_market_adapter_integration_core.ts',
  'tests/test_market_adapter_log_format.ts',
  'tests/test_market_adapter_logic.ts',
  'tests/test_market_adapter_modular.ts',
  'tests/test_market_adapter_precision_guards.ts',
  'tests/test_market_adapter_runtime.ts',
  'tests/test_market_adapter_service.ts',
  'tests/test_market_adapter_signal_gates.ts',
  'tests/test_market_adapter_smoke.ts',
  'tests/test_market_book_xaut.ts',
  'tests/test_market_fee_deduction.ts',
  'tests/test_market_price.ts',
  'tests/test_market_scenarios.ts',
  'tests/test_multi_asset_distribution.ts',
  'tests/test_multi_partial_consolidation.ts',
  'tests/test_multi_partial_edge_cases.ts',
  'tests/test_multifill_opposite_partial.ts',
  'tests/test_native_chain_client.ts',
  'tests/test_native_ecc.ts',
  'tests/test_native_facade.ts',
  'tests/test_native_serial_ops.ts',
  'tests/test_native_serial_types.ts',
  'tests/test_native_subscriptions.ts',
  'tests/test_native_transport.ts',
  'tests/test_native_tx_builder.ts',
  'tests/test_node_failover.ts',
  'tests/test_node_manager.ts',
  'tests/test_node_manager_rpc_protocol.ts',
  'tests/test_open_orders.ts',
  'tests/test_order_grid.ts',
  'tests/test_partial_order_edge_cases.ts',
  'tests/test_patch17_invariants.ts',
  'tests/test_periodic_sync_fill_rebalance.ts',
  'tests/test_pm2_logic.ts',
  'tests/test_pm2_main_output.ts',
  'tests/test_pm2_single_target_output.ts',
  'tests/test_pm2_startup_order.ts',
  'tests/test_pm2_stop_delete_all.ts',
  'tests/test_pool_id_cache.ts',
  'tests/test_precision_integration.ts',
  'tests/test_precision_quantization.ts',
  'tests/test_price_derive.ts',
  'tests/test_price_no_positional.ts',
  'tests/test_price_orientation.ts',
  'tests/test_price_tolerance.ts',
  'tests/test_privatekey_sanitize.ts',
  'tests/test_read_input.ts',
  'tests/test_recent_own_cancels.ts',
  'tests/test_resync_balance_fix.ts',
  'tests/test_resync_duplicate_race.ts',
  'tests/test_resync_invariants.ts',
  'tests/test_rotation_available_funds.ts',
  'tests/test_rotation_order_sizing.ts',
  'tests/test_rotation_source_clear_regression.ts',
  'tests/test_scaled_spread_correction.ts',
  'tests/test_sequential_multi_fill.ts',
  'tests/test_shutdown_reentrancy.ts',
  'tests/test_spread_redistribution_fallback.ts',
  'tests/test_stale_daemon_cleanup.ts',
  'tests/test_startup_decision.ts',
  'tests/test_startup_partial_fill.ts',
  'tests/test_startup_reconcile.ts',
  'tests/test_startup_reconcile_regressions.ts',
  'tests/test_strategy_edge_cases.ts',
  'tests/test_strategy_fixes.ts',
  'tests/test_strategy_logic.ts',
  'tests/test_strategy_reaction_cap_fix.ts',
  'tests/test_strategy_self_rotation_fix.ts',
  'tests/test_strategy_window_budget_distribution.ts',
  'tests/test_subscriptions.ts',
  'tests/test_sync_excess_orphan.ts',
  'tests/test_sync_lock_routing.ts',
  'tests/test_sync_lock_timeout.ts',
  'tests/test_sync_logic.ts',
  'tests/test_targeted_drift_reconcile.ts',
  'tests/test_trade_history.ts',
  'tests/test_transport_connect_noop.ts',
  'tests/test_twentix_only.ts',
  'tests/test_unanchored_spread_correction.ts',
  'tests/test_uncertain_broadcast.ts',
  'tests/test_unlock_control_output.ts',
  'tests/test_unlock_foreign_cred_daemon.ts',
  'tests/test_unlock_foreign_cred_daemon_live.ts',
  'tests/test_unlock_isolated_poll_reject.ts',
  'tests/test_unlock_main.ts',
  'tests/test_unlock_output.ts',
  'tests/test_utils.ts',
  'tests/test_websocket_subscription_flow.ts',
  'tests/test_working_grid.ts',
];

const runLiveTests = process.env.RUN_LIVE_BITSHARES_TESTS === '1';
let skippedLive = 0;

for (const testFile of testFiles) {
  if (liveTestFiles.has(testFile) && !runLiveTests) {
    skippedLive++;
    continue;
  }

  const run = spawnSync(process.execPath, ['--import', 'tsx', testFile], {
    stdio: 'inherit',
    cwd: process.cwd(),
    env: process.env,
  });

  if (run.status !== 0) {
    process.exit(run.status || 1);
  }
}

if (skippedLive > 0) {
  console.log(`\n[SKIPPED ${skippedLive} live test(s) — set RUN_LIVE_BITSHARES_TESTS=1 to run]`);
}
