#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const distTarget = path.join(root, 'dist', 'unlock.js');

if (fs.existsSync(distTarget)) {
  require(distTarget);
} else {
  require('tsx/cjs');
  require(path.join(root, 'unlock.ts'));
}
