module.exports = {
  ...require('./modules/claw_bridge'),
  ...require('./modules/claw_catalog'),
  ...require('./modules/claw_infra'),
  ...require('./modules/claw_manifest'),
  ...require('./modules/claw_skill_md'),
  ...require('./modules/dexbot_profiles'),
  ...require('./modules/honest_ecosystem'),
  ...require('./modules/liquidity_pools'),
  ...require('./modules/decision_loop'),
  ...require('./modules/feed_price_source'),
  ...require('./modules/kibana_price_source'),
  ...require('./modules/position_discovery'),
  ...require('./modules/position_health'),
  ...require('./modules/position_manager_watch'),
  ...require('./modules/zeroclaw_skill'),
  ...require('./modules/zeroclaw_manifest'),
  ...require('./modules/zeroclaw_bridge')
};
